### ISSUE TITLE
Potential Wrong Validation of NTLM Auth. in ConnectionTester

### ISSUE THREAD

**Issue by atanurelmasoglu** [vletoux/pingcastle#152]
Hello Vincent!

While I was analyzing the workflows of the  A-CertEnrollChannelBinding and A-CertEnrollHttp rules, I encountered that the logic behind the ConnectionTester and ConnectionTesterHTTP classes are not working correctly when the Providers for the Web Enrollment or CES are configured to support only NTLM.  When the SendPackets method of the ConnectionTesterHTTP tries to fall back to the NTLM, it returns an empty result in the header. Thus, it returns AuthenticationFailure even if they are up. 

While I was playing around to fix it, the root cause seems like the package variable in the ConnectionTester to initialize NTAuthentication. If it is initialized as the NTLM instead of Negotiate, everything seems fine.

Could you please take a look at that behaviour?

Thanks!

**Comment by vletoux** [comment]
I don't understand what you said: there is a fallback to NTLM
https://github.com/vletoux/pingcastle/blob/d2b15aa3e672371d98c769b234da87689456c4ed/misc/ConnectionTesterHttp.cs#L81-L87

Can you elaborate with the data you have in your context ?

**Comment by atanurelmasoglu** [comment]
1)Set the provider as NTLM for either Web Enrollment or CES.

![image](https://user-images.githubusercontent.com/16972413/200119143-d5f77f46-f4e5-4729-8042-0f53acdb50ad.png)

2)Test the NTLM fallback. CA server not returns the base64 blob and thus, GetAuthenticationRequest returns null which resulted in ConnectionTesterStatus.AuthenticationFailure.

![image](https://user-images.githubusercontent.com/16972413/200119288-0d13276b-7670-4521-ab33-7fe2a0ac1d28.png)

3) Initialize package variable as NTLM, instead of Negotiate and run it again. Everything seems fine.

![image](https://user-images.githubusercontent.com/16972413/200119402-057f4a19-88c0-41b6-99a5-22ebf2b41808.png)

**Comment by vletoux** [comment]
ok I fixed the code
![image](https://user-images.githubusercontent.com/10632326/200123744-d9d4f466-5dff-43cc-b4c5-f5a30d5ca34a.png)

![image](https://user-images.githubusercontent.com/10632326/200123816-bb6a87d0-f766-4a04-af8c-e76e288145b1.png)


Basically there was 2 issues:
1) the NTLM change was not trapped (because the program was expecting a space after NTLM
2) the SSPI stack was not reinitialized to take in account the change of the provider

The fix will be available in the next version (January) or if you paid support you can request an immediate fix

**Comment by atanurelmasoglu** [comment]
Ok, thanks for the fix!
