### ISSUE TITLE
Wrong argument supplied to Test on the TestSignatureRequiredEnabled

### ISSUE THREAD

**Issue by atanurelmasoglu** [vletoux/pingcastle#156]
Hi Vincent,

During the first call of the Test function at the TestSignatureRequiredEnabled, the second argument should be false.
Since the parameter refers to "disableSigning", It needs to be set as false to test with the signature required.

![tempsnip](https://user-images.githubusercontent.com/16972413/207973479-0432ddfb-4baa-4a77-b524-553d4f3330ba.png)

Could you please check that behavior?

In addition to this, testing without the signature in an LDAP Server Signing enforced domain environment returns code 0x8 (strongAuthRequired) on SendPackets at the ConnectionTesterLdap.cs.

![image](https://user-images.githubusercontent.com/16972413/207972557-b33ba9ba-d627-4da8-b15e-09c515494044.png)

Does it seem like a usual one? If it is, adding this error code as an expected value should be more clear.

**Comment by vletoux** [comment]
The code is correct.

The second issue you highlighted is due to the fact that it is tested against ldaps instead of ldap
(ldaps cannot have integrity enabled because of TLS)
This is a bug that has been fixed here: https://github.com/vletoux/pingcastle/commit/cfb4a0e26fa9a9aa0f006053307cdec322845287 but not pushed has a new release because of our paid support policy

**Comment by atanurelmasoglu** [comment]
I 've already tested with the fixed ldap one and got this error message. Also, the second image belongs to an ldap one.

**Comment by vletoux** [comment]
are you sure ?
Quotting your error message
![image](https://user-images.githubusercontent.com/10632326/208059479-c86c4036-9609-491c-8f1a-8e6a165bdb6e.png)

**Comment by atanurelmasoglu** [comment]
Here the scheme is LDAP.

![tempsnip2](https://user-images.githubusercontent.com/16972413/208064042-d252e3b0-a3a0-4f99-85a9-0ed5afaa28c6.png)

**Comment by vletoux** [comment]
You are right.
The arguments here https://github.com/vletoux/pingcastle/blob/d2b15aa3e672371d98c769b234da87689456c4ed/misc/ConnectionTester.cs#L152 and here https://github.com/vletoux/pingcastle/blob/d2b15aa3e672371d98c769b234da87689456c4ed/misc/ConnectionTester.cs#L161 should be reverted

i was confused because I was working in reverted logic.
Indeed, the arg is forwarded here:
https://github.com/vletoux/pingcastle/blob/d2b15aa3e672371d98c769b234da87689456c4ed/misc/ConnectionTester.cs#L318

I added a comment in the code when further review will occur and specifically the meaning of the flags.
```
// from SSPI.h
// #define ISC_REQ_NO_INTEGRITY            0x00800000
// #define ISC_REQ_INTEGRITY               0x00010000
// transformed into System.Net.ContextFlags enum
```


bug fixed for the next version

**Comment by Decoder34** [comment]
Glad to see that we found the spot.
Appreciate for your help and thanks for the fix !
