### ISSUE TITLE
 3.1.5.0 Beta issue with rule P-AdminLogin "Administrator account has been used recently"

### ISSUE THREAD

**Issue by mpgn** [vletoux/pingcastle#207]
By testing the version  3.1.5.0 Beta a rule has been flagged on our domain which was not flagged on version 3.1.0.0: 

>  The native administrator account has been used recently: 0 day(s) ago

![image](https://github.com/vletoux/pingcastle/assets/5891788/0f710131-796c-4adc-9c13-fbe086b2b70f)

Nevertheless, this account is no active on our side and not used since many years.

![image](https://github.com/vletoux/pingcastle/assets/5891788/86056a2b-89b3-4398-892a-a407c6d3562b)

![image](https://github.com/vletoux/pingcastle/assets/5891788/b0b0209d-1674-41ab-a849-4d4281ecc1e6)

So maybe a regression from 3.1 :)

The version 3.1.0.0 does not report this rule.

**Comment by RGAGPB** [comment]
Hi, same problem for me in the latest beta (3.2 in the package name, 3.1.5 in the report), this rule keeps telling me my admin account has been used recently.
I always had the problem because pingcastle was looking at lastlogontimestamp instead of lastlogon, I thought it was supposed to change with this version (the rule description talks about it btw) but I just checked and the lastlogon is indeed September 2021 on all my DCs, so there must still be a little problem 😬 
Merci !

**Comment by mpgn** [comment]
Fixed on the new version 3.2.0.0 beta !
