### ISSUE TITLE
Remove questionmark from exported data headers

### ISSUE THREAD

**Issue by ville87** [vletoux/pingcastle#208]
When exporting table data to e.g. JSON or CSV, the questionmark from the Icon is included in all headers.
CSV Example:
```
SamAccountName ?,"Enabled ?","Active ?","Pwd never Expired ?","Locked ?","Smart Card required ?",[...]
```
JSON Example:
```
{"header":[["SamAccountName ?","Enabled ?","Active ?","Pwd never Expired ?","Locked ?","Smart Card required ?",[...]
```
It would be nice if this could be removed before generating the file.

**Comment by vletoux** [comment]
This is because we are using behing the hood [boostraptable](https://bootstrap-table.com/) to provide the export function.
In the header, the question is here to indicate additional context.
I do not know a css class name to exclude the question mark from the export.
If you can provide it, I'll be happy to add it so the question mark won't be included anymore in the export
