### ISSUE TITLE
2.9.1.0 Inactive User or Computer - Computers without password change in at least 3 months

### ISSUE THREAD

**Issue by stondino00** [vletoux/pingcastle#65]
This rule isn't working correctly.  It's showing me a number that doesn't match the computer section of the report.

**Comment by stondino00** [comment]
Running this in powershell is telling me the machines that have old password changes.  Ping castle is not showing this list however so you don't know where it gets the number it's showing.

get-adcomputer -filter * -properties passwordlastset | select name, passwordlastset | sort passwordlastset

**Comment by vletoux** [comment]
You need to be more precise because i don't understand what the issue is.
I remind that there is filter to exclude disable accounts, and a logic to remove computers which are no longer used (typically using the lastlogontimestamp)

Here is the code:
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/HealthcheckAnalyzer.cs#L731-L743

**Comment by vletoux** [comment]
If you need to discuss about specifics, you can email at support at pingcastle dot com

**Comment by stondino00** [comment]
We were able to fix the issue by running that power shell command that showed us last computer password set and seeing the old entries.  PingCastle stated there were computers that had old password last set but never showed us those exact names of computers.
